POST http://localhost:3500/accounts/createAccount
Content-Type: application/json

{
    "email":"nithish@gmail.com",
    "mobile":"8179221413",
    "password":"nithish"
}

###
POST http://localhost:3500/accounts/login
Content-Type: application/json

{
    "email" : "nithish@gmail.com",
    "mobile":"8179221413",
    "password":"nithish"
}